<?php
include '../conf.php';
    $qIL = "SELECT
            iller.id as PLAKA,
            iller.baslik as IL
            FROM iller";
        $resultIL = $mysqli->query($qIL);
    $qILCE = "SELECT ilce.ilid as PLAKA,
            (select iller.baslik from iller WHERE iller.id = ilce.ilid) as IL,
            ilce.baslik as ILCE
            FROM ilceler ilce";
        $resultILCE = $mysqli->query($qILCE);
 
?>

<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

	<!-- generator="WordPress/5.7.2" created="2021-06-25 09:58" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

	<channel>
		<title>En İyi Okul Hangisi ? Okul Araştır</title>
		<link>https://okularastir.com</link>
		<description>Hangi Okul?</description>
		<pubDate>Fri, 25 Jun 2021 09:58:06 +0000</pubDate>
		<language>tr</language>
		<wp:wxr_version>1.2</wp:wxr_version>
		<wp:base_site_url>https://okularastir.com</wp:base_site_url>
		<wp:base_blog_url>https://okularastir.com</wp:base_blog_url>
        <?php
            function url_make($str){
                $before = array('ı', 'ğ', 'ü', 'ş', 'ö', 'ç', 'İ', 'Ğ', 'Ü', 'Ö', 'Ç', 'Ş'); // , '\'', '""'
                $after   = array('i', 'g', 'u', 's', 'o', 'c', 'i', 'g', 'u', 'o', 'c', 'S'); // , '', ''
            
                $clean = str_replace($before, $after, $str);
                $clean = preg_replace('/[^a-zA-Z0-9 ]/', '', $clean);
                $clean = preg_replace('!\s+!', '-', $clean);
                $clean = strtolower(trim($clean, '-'));
            return $clean;
            }
            while($row = $resultIL->fetch_assoc()){
                $il = $row['IL'];
                $rIL = preg_replace('/\W+/', '-', strtolower(trim($il)));
        ?>

		<wp:term>
			<wp:term_taxonomy><![CDATA[job_listing_region]]></wp:term_taxonomy>
			<wp:term_slug><![CDATA[<?=url_make($IL)?>]]></wp:term_slug>
			<wp:term_parent><![CDATA[]]></wp:term_parent>
			<wp:term_name><![CDATA[<?=$il?>]]></wp:term_name>
			<wp:termmeta>
				<wp:meta_key><![CDATA[apus_icon_type]]></wp:meta_key>
				<wp:meta_value><![CDATA[font]]></wp:meta_value>
			</wp:termmeta>
			<wp:termmeta>
				<wp:meta_key><![CDATA[apus_icon_font]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:termmeta>
			<wp:termmeta>
				<wp:meta_key><![CDATA[apus_icon_image]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:termmeta>
		</wp:term>
        <?php }
        while($row = $resultILCE->fetch_assoc()){
            $il = $row['IL'];
            $ilce = $row['ILCE'];
            $rIL = preg_replace('/\W+/', '-', strtolower(trim($il)));
            $rILCE = preg_replace('/\W+/', '-', strtolower(trim($ilce)));
            ?>
		<wp:term>
			<wp:term_taxonomy><![CDATA[job_listing_region]]></wp:term_taxonomy>
			<wp:term_slug><![CDATA[<?=url_make($il).'-'.url_make($ilce);?>]]></wp:term_slug>
			<wp:term_parent><![CDATA[<?=$il?>]]></wp:term_parent>
			<wp:term_name><![CDATA[<?=$ilce?>]]></wp:term_name>
			<wp:termmeta>
				<wp:meta_key><![CDATA[apus_icon_type]]></wp:meta_key>
				<wp:meta_value><![CDATA[font]]></wp:meta_value>
			</wp:termmeta>
			<wp:termmeta>
				<wp:meta_key><![CDATA[apus_icon_font]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:termmeta>
			<wp:termmeta>
				<wp:meta_key><![CDATA[apus_icon_image]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:termmeta>
		</wp:term>
        <?php } ?>
	</channel>
</rss>
	